# Generated by Django 4.2 on 2023-04-20 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='sequence',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
