# Generated by Django 4.2 on 2023-04-20 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_location_sequence'),
    ]

    operations = [
        migrations.AddField(
            model_name='workorder',
            name='priority',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
