### Post location create
POST  http://localhost:8000/kanban-api/location/create/
Content-Type: application/json

{
    "name": "new location",
    "sequence": "10"
}

### Post part create
POST http://localhost:8000/kanban-api/part/create/
Content-Type: application/json

{
    "name": "new part",
    "description": "test description"
}

### Get workorder list
GET http://localhost:8000/kanban-api/workorder/list/
Content-Type: application/json