### Put location list
PUT http://localhost:8000/kanban-api/location/list/
Content-Type: application/json

[
    {
        "id": 21,
        "name": "This is a new location",
        "sequence": 20
    },
    {
        "id": 23,
        "name": "another new location",
        "sequence": 30
    }
]

### Get part list
GET http://localhost:8000/kanban-api/part/list/
Content-Type: application/json

### Get workorder list
GET http://localhost:8000/kanban-api/workorder/list/
Content-Type: application/json