FROM public.ecr.aws/lambda/python:3.8

# Set work directory
WORKDIR ${LAMBDA_TASK_ROOT}

# Install dependencies
COPY requirements.txt .
RUN pip install -r requirements.txt

# Copy project
COPY manufacturing_kanban/. .
COPY zappa_settings.py .

# Grab the zappa handler.py and put it in the working directory
RUN ZAPPA_HANDLER_PATH=$( \
    python -c "from zappa import handler; print (handler.__file__)" \
    ) \
    && echo $ZAPPA_HANDLER_PATH \
    && cp $ZAPPA_HANDLER_PATH .


CMD [ "handler.lambda_handler" ]