version: "3.9"
services:
  web:
    build:
      context: ..
      dockerfile: docker/Dockerfile_local
    command: python manufacturing_kanban/manage.py runserver 0.0.0.0:8000
    image: demo-manufacturing-kanban
    volumes:
      - ..:/app
    env_file:
      - ./.env.local
    ports:
      - "8000:8000"